config/routes.rb
Rails.application.routes.draw do

  get 'tweets' => 'tweets#index'
  resources :tweets do
    collection do
      post :confirm
    end
  end
  
  root 'top#index'

  

end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
    validates :content, presence: true
    validates :content, length: { maximum: 140 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def index
    @tweets = Tweet.all
  end
  
  def new
    @tweet = Tweet.new
  end
  
  def create
    @tweet = Tweet.create(tweet_params)
    if @tweet.save
      redirect_to tweets_path, notice: "つぶやきを投稿しました！"
    else
      render 'new'
    end
  end
  
  def edit
    @tweet = Tweet.find(params[:id])
  end
  
  def update
    @tweet = Tweet.find(params[:id])
    @tweet.update(tweet_params)
    redirect_to tweets_path, notice: "つぶやきを更新しました！"

  end
  
  def destroy
    @tweet = Tweet.find(params[:id])
    @tweet.destroy
    redirect_to tweets_path, notice: "つぶやきを削除しました！"
  end
  
  def confirm
    @tweet = Tweet.new(tweet_params)
    render :new if @tweet.invalid?
  end
  
  
private
  def tweet_params
    params.require(:tweet).permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_tweets_path
    elsif action_name == 'edit'
      tweet_path
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Twitter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>

  <header>
    <ul>
      <li><%= link_to "トップページ", root_path %></li>
      <li><%= link_to "つぶやく", new_tweet_path %></li>
      <li><%= link_to "つぶやき一覧", tweets_path %></li>
    </ul>
  </header>

<%= yield %>

  <footer>
    <p>運営:Okada Tomohiro</p>
    <p>© 2016-2017 Copyright Okada Company</p>
  </footer>

</body>
</html>

app/views/top/index.html.erb
<div class="container">
<section class="main-header">
<center>
  <a href="tweets/new"><img src="<%= asset_path "logo.png" %>"></a>
</center>
</section>
<div id="page-top-btn" class="page-top-btn">
    <p><a class="move-page-top" id="move-page-top">▲</a></p>
</div>
<section class="about">
  <h1>Twitter へようこそ</h1>
  <p>
     Twitterは、つぶやきを通じて繋がるSNSアプリです。<br>
     普段の気持ちをつぶやいたり、フォロワーとのメッセージで多くの人と繋がりましょう。
     <li><%= link_to "つぶやいてみる", new_tweet_path, class: 'btn btn-default btn-block'%></li><br>
     <li><%= link_to "つぶやきをみる", tweets_path, class: 'btn btn-default btn-block' %></li>
  </p>
</section>
</br>
</div>

app/views/tweets/_form.html.erb
<%= form_for(@tweet, url: choose_new_or_edit) do |f| %>
  <% if @tweet.errors.any? %>
    <div id="error_explanation">
      <!--# バリデーションエラーの件数を表示します。-->
      <h2><%= @tweet.errors.count %>件のエラーがあります。</h2>

      <ul>
      <!--# @blog.errorsは@blogをバリデーションした際のエラー情報です。-->
      <!--# full_messagesは複数のエラーメッセージを表します。-->
      <% @tweet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.label :今何やってる？ %>
  <%= f.text_field :content, class: 'form-control' %>
  <br>
  <%= f.submit 'つぶやき投稿', class: 'btn btn-primary btn-block' %>
<% end %>

<%= link_to "つぶやき一覧に戻る", tweets_path %>

app/views/tweets/confirm.html.erb
<div class="container">
  <div class="wrapper col-md-8 col-md-offset-2 col-sm-10">
      <h3>以下の内容で、送信する。</h3>

<%= form_for(@tweet) do |f| %>
  <%= f.hidden_field :content %>
  <p>つぶやき:<%= @tweet.content %></p>
  <%= f.submit "登録", class: 'btn btn-primary btn-block' %>
<% end %>

<%= form_for(@tweet, url: choose_new_or_edit) do |f| %>
  <%= f.hidden_field :content %>
  <%= f.submit "戻る", name: 'back', class: 'btn btn-default btn-block' %>
  <% end %>
    </div>
</div>

app/views/tweets/edit.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
<h2>つぶやきを編集する</h2>

<%=render 'form' %>
  </div>
</div>

app/views/tweets/index.html.erb
<div class="container">
<div class="wrapper col-md-8 col-md-offset-2 col-sm-10">
  <div id="page-top-btn" class="page-top-btn">
    <p><a class="move-page-top" id="move-page-top">▲</a></p>
</div>
<p><%= notice %></p>
<h1>つぶやき一覧</h1>
<%= link_to "つぶやく", new_tweet_path, class: 'btn btn-default' %>
<% @tweets.each do |tweet| %>
<div class="row">
    <p><%=tweet.content%></p>
  <%= link_to "編集", edit_tweet_path(tweet.id), class: 'btn btn-primary btn-sm' %>
  <%= link_to "削除", tweet_path(tweet.id), method: :delete, data:{confirm: '本当に削除していいですか？'}, class: 'btn btn-default btn-sm' %>
</div>
  <% end %>

</div>
</div>

app/views/tweets/new.html.erb
<div class="container">
  <div class="col-md-6 col-md-offset-3 col-sm-10 col-sm-offset-1">
      <h2>つぶやきを作成する</h2>
      <%=render 'form' %>
  </div>
</div>